### PR TITLE
feat:  merge bamfin and bamfout in to poof #167

### PR DESCRIPTION
**Pull request by rhoxie21**
Merge bamf which is captured in issue #167 

I solved this by merging bamfin and bamfout into poof with an additional argument; not sure if this is what was meant by this issue.

### CODE REVIEW

**Comment by Synival** [comment]
@rhoxie21  IIRC the goal here was to have some shared code between these two commands because they were virtually identical. But in the current code I'm looking it, they're both nice and small little commands...  they're probably fine as they are :)

**Comment by rhoxie21** [comment]
@Synival - agreed, I wasn't entirely sure what was wanted here since they both were small.  I can close this out; I assume we should close the issue as well?

**Comment by Synival** [comment]
@rhoxie21 Issue closed! :) I'll try to review some of the issues I posted after I get this giant patch out. Hopefully late tonight or tomorrow

**Comment by Synival** [comment]
@rhoxie21 I just closed the pull request as well. Thanks for the patch, sorry it wasn't needed after all...

**Pull request closed without merging**
